version = 0.1
[default.deploy.parameters]
stack_name = "backend-ecofrenzy"
resolve_s3 = true
s3_prefix = "backend-ecofrenzy"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
