version = 0.1
[default.deploy.parameters]
stack_name = "upload-image"
resolve_s3 = true
s3_prefix = "upload-image"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
